### ISSUE TITLE
Collection Layout not working

### ISSUE THREAD

**Issue by thatvirtualboy** [mmistakes/jekyll-theme-basically-basic#121]
I've created collection page called `menu.markdown` with front matter:

```
---
title: Release Menu
layout: collection
permalink: /releasemenu/
collection: releasemenu
entries_layout: grid
image: /assets/images/release-menu.png
---
```

I've added `collection: releasemenu` to a number of posts but they aren't showing up on `menu.markdown`

I've even added them into their own `_releasemenu` folder like your `_recipe` example, but the posts aren't showing up on the page. Any ideas?

**Comment by thatvirtualboy** [comment]
Resolved. Didn't realize the _config.yml needed (requirement missing from the Collection documentation).

```
collections:
  releasemenu:
    output: true
    permalink: /:collection/:path/
```
