### ISSUE TITLE
Remove same title on homepage

### ISSUE THREAD

**Issue by Funeoz** [mmistakes/jekyll-theme-basically-basic#76]
I would like to remove that big title which is above the "posts" title.
![l](https://user-images.githubusercontent.com/31157012/47497276-c1358800-d859-11e8-8233-b199d5beda63.png)
 How could I do that ?

**Comment by mmistakes** [comment]
https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_includes/page-intro.html#L15

**Comment by mmistakes** [comment]
https://github.com/mmistakes/jekyll-theme-basically-basic#layout-post

```yaml
# optional alternate title to replace page.title at the top of the page
alt_title: "Your optional home page title"

# optional sub-title below the page title
sub_title: "Optional sub-title"
```
